jobs:
  - name: 'cleanup-backup-syncthing'
    jobtype: 'exec'
    container: 'database'
    schedule: '0 0 12 * * *'
    command: 'foobar'
  - name: 'echo-foobar'
    jobtype: 'run'
    image: 'alpine:latest'
    environment:
      - 'foo=bar'
    schedule: '0 0 14 * * *'
  - name: 'bar'
    jobtype: 'exec'
    container: 'webserver'
    schedule: '0 0 18 * * *'
    user: 'root'
    command: "/bin/sh -c 'echo iteration-0; sleep 10; echo iteration-1; sleep 10; echo iteration-2; sleep 10; echo iteration-3'"
  - name: 'foobar'
    jobtype: 'run'
    image: 'alpine:latest'
    schedule: '0 20 20 * * *'
    volumes:
      - '/tmp:/host/tmp:ro'
    command: "/bin/sh -c 'echo foobar'"
  - name: 'sleep-20'
    jobtype: 'run'
    image: 'alpine:3.18.4'
    schedule: '0 20 20 * * *'
    command: 'sleep 20'
  - name: 'boofar'
    jobtype: 'run'
    image: 'melvyndekort/scheduler:latest'
    schedule: '0 10 6 * * *'
