[tool.poetry]
name = "scheduler"
version = "0.1.0"
description = ""
authors = ["Melvyn de Kort <melvyn@mdekort.nl>"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"
docker = "^7.1"
requests = "<2.33.0" # Temporarily pin version because of https://github.com/docker/docker-py/issues/3256
Flask = "^3.0"
gunicorn = "^23.0"
cachetools = "^5.5"
supervisor = "^4.2"
APScheduler = "^3.10"
slack-sdk = "^3.31"

[tool.poetry.dev-dependencies]
pytest = "^8.3"
pytest-cov = "^5.0"
pylint = "^3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
